### ISSUE TITLE
Suite one used by generate script getting stalled

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#192]
It worked once for me this morning, out of near 10 runs. I tried changing the `sleep` times in the suite definition with no luck.

It is running for a long time, until it displays

```
2019-08-19T22:25:03Z INFO - [retrying.20000101T0000Z] -health check settings: execution timeout=None
2019-08-19T22:25:03Z CRITICAL - [retrying.20000101T0000Z] status=running: (received)failed/EXIT at 2019-08-19T22:25:03Z for job(02)
2019-08-19T22:25:03Z CRITICAL - [retrying.20000101T0000Z] -job(02) failed
2019-08-19T22:25:05Z WARNING - suite stalled
2019-08-19T22:25:05Z WARNING - Unmet prerequisites for sleepy.20000101T0000Z:
2019-08-19T22:25:05Z WARNING -  * checkpoint.20000101T0000Z succeeded
2019-08-19T22:25:05Z WARNING - Unmet prerequisites for waiting.20000101T0000Z:
2019-08-19T22:25:05Z WARNING -  * checkpoint.20000101T0000Z succeeded
2019-08-19T22:25:05Z WARNING - Unmet prerequisites for failed.20000102T0000Z:
2019-08-19T22:25:05Z WARNING -  * succeeded.20000102T0000Z succeeded
2019-08-19T22:25:05Z WARNING -  * eventually_succeeded.20000102T0000Z succeeded
```

![Screenshot_2019-08-20_10-25-36](https://user-images.githubusercontent.com/304786/63305000-4d5cf280-c339-11e9-993c-faf5c3ea7748.png)

Then nothing happens for several minutes. The last time I tried, it started at `2019-08-20T10:44:19` and I killed it at `2019-08-20T10:58:29`.

When I killed it, the log had several similar messages:

```
2019-08-19T22:56:47Z INFO - [client-command] pb_entire_workflow kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:56:52Z INFO - [client-command] pb_entire_workflow kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:56:57Z INFO - [client-command] identify kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:56:57Z INFO - [client-command] pb_entire_workflow kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:57:02Z INFO - [client-command] pb_entire_workflow kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:57:07Z INFO - [client-command] identify kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:57:07Z INFO - [client-command] pb_entire_workflow kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:57:12Z INFO - [client-command] pb_entire_workflow kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:57:17Z INFO - [client-command] identify kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:57:17Z INFO - [client-command] pb_entire_workflow kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:57:22Z INFO - [client-command] pb_entire_workflow kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:57:27Z INFO - [client-command] identify kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:57:27Z INFO - [client-command] pb_entire_workflow kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:57:32Z INFO - [client-command] pb_entire_workflow kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:57:37Z INFO - [client-command] identify kinow@kinow-VirtualBox:cylc-uiserver
2019-08-19T22:57:37Z INFO - [client-command] pb_entire_workflow kinow@kinow-VirtualBox:cylc-uiserver
^C2019-08-19T22:57:38Z ERROR -
	Traceback (most recent call last):
	  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/cylc/flow/scheduler.py", line 252, in start
	    self.run()
	  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/cylc/flow/scheduler.py", line 1578, in run
	    sleep(self.INTERVAL_MAIN_LOOP - elapsed)
	KeyboardInterrupt
2019-08-19T22:57:38Z CRITICAL - Suite shutting down - 
2019-08-19T22:57:39Z INFO - DONE
cp: cannot stat '/home/kinow/cylc-run/one/work/20000102T0000Z/checkpoint/checkpoint': No such file or directory
```

**Comment by kinow** [comment]
As workaround, in my branch I've updated the `get_checkpoint.py` with the fields I wanted, then before shutting down the workflow, I used GraphiQL to retrieve the output of my query and replaced it manually in `checkpoint.js`. :tada:

**Comment by matthewrmshin** [comment]
Any clues in the log for the job e.g. `~/cylc-run/one/log/job/20000101T0000Z/retrying/02/job.err`  (and `job.xtrace`) on why it failed?

**Comment by kinow** [comment]
@matthewrmshin I think you just solved the issue!

```
/home/kinow/.rvm/scripts/rvm: line 174: __rvm_ensure_is_a_function: command not found
/home/kinow/.rvm/scripts/rvm: line 175: __rvm_setup: command not found
/home/kinow/.rvm/scripts/rvm: line 178: __rvm_version_installed: command not found
/home/kinow/.rvm/scripts/rvm: line 245: __rvm_teardown: command not found
2019-08-20T21:24:17Z CRITICAL - failed/EXIT
```

Although my terminal doesn't have any error messages, and other applications work, I remember some time ago the same happened to me. Just removed [rvm](https://rvm.io/) from my console and now it passed with no errors! :tada: (will make a mental note to not install rvm again, or check it before reporting about a broken workflow/suite).

Thanks
