### ISSUE TITLE
Console error: chunk-vendors.f6e0f0e5.js:53 Uncaught Invariant Violation: Invariant Violation: 12 (see https://github.com/apollographql/invariant-packages)

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#224]
Browser console has the following after building the app for production mode, and running with the Hub.

![image](https://user-images.githubusercontent.com/304786/64921290-8ba0e100-d815-11e9-926a-519eff17b4d1.png)

```
chunk-vendors.f6e0f0e5.js:53 Uncaught Invariant Violation: Invariant Violation: 12 (see https://github.com/apollographql/invariant-packages)
    at new e (http://localhost:8000/user/kinow/js/chunk-vendors.f6e0f0e5.js:53:24154)
    at u (http://localhost:8000/user/kinow/js/chunk-vendors.f6e0f0e5.js:53:24379)
    at t.query (http://localhost:8000/user/kinow/js/chunk-vendors.f6e0f0e5.js:7:90152)
    at e.t.query (http://localhost:8000/user/kinow/js/chunk-vendors.f6e0f0e5.js:7:101982)
    at e.value (http://localhost:8000/user/kinow/js/chunk-6a546238.843e1a45.js:1:7212)
    at http://localhost:8000/user/kinow/js/chunk-6a546238.843e1a45.js:1:8561
```

**Comment by kinow** [comment]
In development mode the error we have when we

1. Open the workflows page
2. Go back to the dashboard

Appears to be the same error, but with better description:

![image](https://user-images.githubusercontent.com/304786/64926946-23272380-d858-11e9-8517-ad53ec377256.png)

**Comment by kinow** [comment]
Ah! I think I got it. The `workflowService` is still there, the singleton was never destroyed. And it has no query (notice the empty `elements` in the `query` object).

![image](https://user-images.githubusercontent.com/304786/64927019-5cac5e80-d859-11e9-8d53-9129de8f444b.png)

And we can see from the development exception, that the error is coming from ApolloClient.

**Comment by kinow** [comment]
Closing as duplicate of #226. There is a better description and the error is more clear in that issue, as this one was from the exception running the app in production mode.
