### ISSUE TITLE
Mutation form task validation - prevent empty inputs

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#885]
#### Describe the problem

The mutation form can be submitted with a non-filled out task input:

<img src="https://user-images.githubusercontent.com/61982285/149824051-44c02336-0ae1-47a9-b97a-39fea80481db.png" width="450"/>

It looks like everything worked. But in the workflow log:
```
INFO - Processing 1 queued command(s)
WARNING - Traceback (most recent call last):
      File "~/github/cylc-flow/cylc/flow/scheduler.py", line 844, in process_command_queue
        n_warnings: Optional[int] = self.get_command_method(name)(
      File "~/github/cylc-flow/cylc/flow/scheduler.py", line 932, in command_release
        return self.pool.release_held_tasks(task_globs)
      File "~/github/cylc-flow/cylc/flow/task_pool.py", line 1060, in release_held_tasks
        itasks, future_tasks, unmatched = self.filter_task_proxies(
      File "~/github/cylc-flow/cylc/flow/task_pool.py", line 1594, in filter_task_proxies
        future_matched, unmatched = self.match_future_tasks(
      File "~/github/cylc-flow/cylc/flow/task_pool.py", line 1626, in match_future_tasks
        or contains_fnmatch(id_)
      File "~/github/cylc-flow/cylc/flow/id_cli.py", line 350, in contains_fnmatch
        return bool(FN_CHARS.search(string))
    TypeError: expected string or bytes-like object
WARNING - expected string or bytes-like object
WARNING - Command failed: release([None])
```

#### Expected behaviour

The mutation form should validate and not be able to be submitted with the non-filled in task input.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
This may be a consequence of #1003
